version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "5000:5000"
    expose:
      - 5000
    env_file:
      - .env
    container_name: "backend"
    command: [sh, -c, 'npm run start']
    volumes:
      - .:/app:delegated
      - /app/node_modules

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    container_name: "nginx"
    ports:
      - '80:80'

