export const envConfig = {
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
  CONNECTION_STRING: 'CONNECTION_STRING',
  NODEMAILER_USER: 'NODEMAILER_USER',
  NODEMAILER_PASS: 'NODEMAILER_PASS',
  APP_SECRET: 'APP_SECRET',
  JWT_SECRET: 'JWT_SECRET',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  JWT_ACCESS_LIFESPAN: 'JWT_ACCESS_LIFESPAN',
  JWT_REFRESH_LIFESPAN: 'JWT_REFRESH_LIFESPAN',
  JWT_ALGORITHM: 'JWT_ALGORITHM',
  JWT_ISSUER: 'JWT_ISSUER',
};

